feat: move item position in appListView free sorting mode
linuxdeepin/dde-launchpad pull request #121
Opened 2024-03-18 11:08 UTC by yixinshark

move item position in appListView free sorting mode

Log: move item position in appListView free sorting mode
Influence: app listview move item position

2024-03-18 11:45 UTC, BLumia requested changes
目前的拖拽实现应该只能满足列表内的拖拽，恐怕没法满足从文件夹拖拽到列表，以及从列表拖拽到任务栏之类的需求。需要调整成和目前全屏的拖拽类似的方案，或者其它更好的方案（如果有）。

另外关于 `m_arrangedItems` 的修改需要 revert 掉，参见 review comment。

2024-03-18 11:45 UTC, BLumia commented on src/models/freesortproxymodel.h
> +    QStringList m_arrangedItems;
关于尝试自己维护另一份 m_arrangedItems 的逻辑需要回退掉。排序问题是之前 lessThan 写的有问题（https://github.com/linuxdeepin/dde-launchpad/commit/8ffa679d5a13ff8a003dc9f82a512659397951a0 ）。

2024-03-19 10:16 UTC, yixinshark commented on src/models/freesortproxymodel.h
> +    QStringList m_arrangedItems;
done。之前提交为测试代码。已重新修改。

2024-03-20 03:29 UTC, BLumia approved these changes

2024-03-20 05:12 UTC, merged