refact: updating launchedTimes from DConfig
linuxdeepin/dde-launchpad pull request #130
Opened 2024-03-25 01:39 UTC by 18202781743

Launching app by `dde-am` tools instead of calling dbus directly.
Updating launchedTimes from DConfig.

2024-03-25 01:54 UTC, ComixHe commented
+1

2024-03-25 01:55 UTC, 18202781743 commented
https://github.com/linuxdeepin/dde-application-manager/pull/178

2024-03-27 01:59 UTC, zccrs requested changes

2024-03-27 01:59 UTC, zccrs commented on src/ddeintegration/appmgr.cpp
> +        qWarning() << "Failed to launch the desktopId:" << desktopId << process.errorString();
QProcess::errorString 应该只能报告出 QProcess 自身的错误信息，不会在进程未正常退出时报告进程的错误信息，这里要输出进程的标准输出、以及标准错误输出。

2024-03-27 03:38 UTC, 18202781743 commented on src/ddeintegration/appmgr.cpp
> +        qWarning() << "Failed to launch the desktopId:" << desktopId << process.errorString();
目前错误时不输出QProcess的错误信息吧,错误时,获取到的企业微信等输出信息太多了,

2024-03-29 09:48 UTC, BLumia approved these changes

2024-03-29 09:49 UTC, merged